version: '3'

services:
  hdc-mongo:
    container_name: hdc-mongo
    build: .
    ports:
      - "27017:27017"
    ulimits:
      nproc: 32768
    healthcheck:
      test: echo 'db.stats().ok' | mongo hdc-mongo:27017/hdc --quiet
      interval: 5s
      timeout: 5s
      retries: 12

  mongo-express:
      container_name: mongo-express-hdc
      image: 'mongo-express'
      ports:
        - "8081:8081"
      depends_on:
        - hdc-mongo
      environment:
        - ME_CONFIG_MONGODB_SERVER=hdc-mongo
      #   - ME_CONFIG_MONGODB_PORT=27017
    #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
    #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    #     - ME_CONFIG_MONGODB_AUTH_USERNAME=dataprev
    #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=dataprev
    #     - ME_CONFIG_BASICAUTH_USERNAME=dataprev
    #     - ME_CONFIG_BASICAUTH_PASSWORD=dataprev

